### ISSUE TITLE
npm installation issue

### ISSUE THREAD

**Issue by Luca5om3** [sorare/crypto#15]
Hi, I can't install crypto even with a fresh start:

C:\Users\Utente\Desktop>mkdir test1

C:\Users\Utente\Desktop>cd test1

C:\Users\Utente\Desktop\test1>node -v
v18.13.0

C:\Users\Utente\Desktop\test1>npm -v
9.2.0

C:\Users\Utente\Desktop\test1>npm install @sorare/crypto
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Utente\\node_modules\\bigint-buffer',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Utente\node_modules\bigint-buffer'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Utente\\node_modules\\bigint-buffer'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Utente\\node_modules\\ffi-napi',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Utente\node_modules\ffi-napi'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Utente\\node_modules\\ffi-napi'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Utente\\node_modules\\bigint-buffer',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Utente\node_modules\bigint-buffer'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Utente\\node_modules\\bigint-buffer'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Utente\\node_modules\\ffi-napi',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Utente\node_modules\ffi-napi'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Utente\\node_modules\\ffi-napi'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\Utente\node_modules\@sorare\crypto
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c (test -n "$USE_STARKWARE_CRYPTO_CPP" && node-gyp rebuild) || true
npm ERR! "test" non � riconosciuto come comando interno o esterno,
npm ERR!  un programma eseguibile o un file batch.
npm ERR! "true" non � riconosciuto come comando interno o esterno,
npm ERR!  un programma eseguibile o un file batch.

**Comment by utay** [comment]
Hi @Luca5om3, this looks like an npm issue on Windows that is not related to this library directly. 2 related issues that might help:
- https://stackoverflow.com/questions/55212864/error-ebusy-resource-busy-or-locked-rmdir
- https://stackoverflow.com/questions/55081270/getting-error-ebusy-resource-busy-or-locked

Maybe you can also try to delete `C:\Users\Utente\node_modules` and retry
