### ISSUE TITLE
Npm Install issue on Windows machine

### ISSUE THREAD

**Issue by artyomabrahamyan** [sorare/crypto#17]
Hi, when I try to install @sorare/crypto on a fresh project I get the follogin error 

```
npm ERR! code 1
npm ERR! path C:\Users\AramKocharyan\Desktop\src\layerswap-blockchain-js\node_modules\@sorare\crypto
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c (test -n "$USE_STARKWARE_CRYPTO_CPP" && node-gyp rebuild) || true
npm ERR! 'test' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
npm ERR! 'true' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AramKocharyan\AppData\Local\npm-cache\_logs\2023-01-23T15_17_53_152Z-debug-0.log
```

It seems that the issue is the 

**"install": "(test -n \"$USE_STARKWARE_CRYPTO_CPP\" && node-gyp rebuild) || true"** script in the package.json which is in bash-style and can not be run on Windows.

Please advice.

**Comment by badrghilani** [comment]
Same issue encountered on a Windows machine. Impossible to install using npm, and can't use the python starkware library since it doesn't support the new signature including the "fee".

Please help or suggest any other alternative.

**Comment by utay** [comment]
Hi @artyomabrahamyan @badrghilani, apologies for this issue.

While we're working on making it fully work on Windows, you should be able to replace:
```
"install": "(test -n \"$USE_STARKWARE_CRYPTO_CPP\" && node-gyp rebuild) || true"
```
with:
```
"install": "exit 0"
```
in package.json as a workaround.

**Comment by artyomabrahamyan** [comment]
Hi, @utay. Thank you for response. 

Where should the `"install"` command be changed, isn't that a part of your source code?

**Comment by utay** [comment]
@artyomabrahamyan Indeed it is, sorry, I initially assumed that you cloned this repo and that you could modify package.json. I think version 1.2.1 should work on Windows if you want to try that for the moment

**Comment by lPernod-sorare** [comment]
@artyomabrahamyan As this lib no longer depends on CPP bindings, the install script (and the entire package) should now work properly on Windows
